batch_size: 8
fft_length: 384
frame_length: 256
frame_step: 160
input_shape:
- 414
- 193
learning_rate: 0.0001
max_spectrogram_length: 414
max_text_length: 31
model_path: Models\05_sound_to_text\202310070653
train_epochs: 1000
train_workers: 20
vocab: 'abcdefghijklmnopqrstuvwxyz '
